project:
  type: book

book:
  title: "DevOps Carpentry"
  subtitle: "A Researcher's Guide to the Open Source Ecosystem"
  author: "Matthias Bannert"
  date: "7/12/2022"
  search: true
  sharing: [twitter]
  chapters:
    - index.qmd
    - intro.qmd
    - stack-developer-toolkit.qmd
    - programming.qmd
    - interaction.qmd
    - version-control.qmd
    - data-management.qmd
    - infrastructure.qmd
    - automation.qmd
    - community.qmd
    - publishing.qmd
    - case-studies.qmd
    - appendix.qmd
    - references.qmd

bibliography: references.bib
execute: 
  freeze: true
format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: krantz
  #   pdf-engine: pdflatex
  #   toc: true
  #   keep-tex: true
  #   lof: true
  #   lot: true
  #   fontsize: 12pt
  #   hyperrefoptions: 
  #     - linktoc=none
    
